import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Roboto_Slab,
  EB_Garamond,
  Libre_Baskerville,
  Roboto,
  Open_Sans,
  Quattrocento,
  Bubblegum_Sans,
  Space_Mono,
  Cabin,
  Arvo,
  Montserrat,
  Noto_Sans,
  Inter,
  TikTok_Sans,

} from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from "@clerk/nextjs";
import localFont from 'next/font/local'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const robotoSlab = Roboto_Slab({
  variable: "--font-roboto-slab",
  subsets: ["latin"],
})

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
  weight: "500",
})

const libreBaskerville = Libre_Baskerville({
  variable: "--font-libre-baskerville",
  subsets: ["latin"],
  weight: "400",
})

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
})

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
})

const quattrocento = Quattrocento({
  variable: "--font-quattrocento",
  subsets: ["latin"],
  weight: "700",
})

const bubblegumSans = Bubblegum_Sans({
  variable: "--font-bubblegum-sans",
  subsets: ["latin"],
  weight: "400",
})

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: "700"
})

const cabin = Cabin({
  variable: "--font-cabin",
  subsets: ["latin"],
})

const arvo = Arvo({
  variable: "--font-arvo",
  subsets: ["latin"],
  weight: "400"
})

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: "500"
})

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  // weight: "400"
})

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: "400"
})

const tiktok = TikTok_Sans({
  variable: "--font-tiktok-sans",
  subsets: ["latin"],
  weight: "400"
})

const charter = localFont({
  src: '../../public/fonts/charter_regular-webfont.woff',
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <TRPCReactProvider>
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${geistSans.variable} 
            ${geistMono.variable} 
            ${robotoSlab.variable} 
            ${ebGaramond.variable} 
            ${libreBaskerville.variable} 
            ${roboto.variable} 
            ${openSans.variable}
            ${quattrocento.variable}
            ${bubblegumSans.variable}
            ${spaceMono.variable}
            ${cabin.variable}
            ${arvo.variable}
            ${montserrat.variable}
            ${notoSans.variable}
            ${inter.variable}
            ${tiktok.variable}
            ${charter.className}
            antialiased 
            font-tiktok-sans
            `}
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Toaster />
              {children}
            </ThemeProvider>
          </body>
        </html>
      </TRPCReactProvider>
    </ClerkProvider>

  );
}
